_InzLangCode=en
_InzEnglishName=English
_InzNlsName=English
msscf.cfcli.ApplicationPropertiesNotFound=application.properties not found in classpath resources
msscf.cfcli.CouldNotLoadApplicationProperties=Failed to load application properties from application.properties
msscf.cfcli.UserDefaultPropertiesNotFound=user-default.properties not found in classpath resources
msscf.cfcli.FailedToLoadUserDefaultProperties=Failed to load user default properties from user-default.properties
msscf.cfcli.FailedToLoadUserProperties=Failed to load user properties from .cfcli.properties
msscf.cfcli.NewUserPropsFileCreatedAt=A new user properties file has been created at: %s
msscf.cfcli.PleaseCustomizeThisFile=Please customize this file before running the application again.
msscf.cfcli.NeitherUserDefaultNorApplicationPropertiesFound=user-default.properties and application.properties not found in classpath resources
msscf.cfcli.FailedToCreateUserPropertiesFile=Failed to create user properties file "%s": %s
msscf.cfcli.rethrow=ERROR: Caught and rethrew %1$s during %2$2() - %3$s

