#User configuration options
jakarta.persistence.jdbc.url=jdbc:postgresql://127.0.0.1:5432/cfclidb
jakarta.persistence.jdbc.user=postgres
jakarta.persistence.jdbc.password=pgpassword
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# cfsecdb specific user configuration options
#cfsecdb.hibernate.hbm2ddl.auto=create
cfsecdb.hibernate.hbm2ddl.auto=update
cfsecdb.hibernate.show_sql=false
cfsecdb.hibernate.format_sql=false
cfsecdb.hibernate.use_sql_comments=false
cfsecdb.hikari.maximum-pool-size=10
cfsecdb.hikari.minimum-idle=2

# cfintdb specific user configuration options
#cfintdb.hibernate.hbm2ddl.auto=create
cfintdb.hibernate.hbm2ddl.auto=update
cfintdb.hibernate.show_sql=false
cfintdb.hibernate.format_sql=false
cfintdb.hibernate.use_sql_comments=false
cfintdb.hikari.maximum-pool-size=10
cfintdb.hikari.minimum-idle=2

# cfbamdb specific user configuration options
#cfbamdb.hibernate.hbm2ddl.auto=create
cfbamdb.hibernate.hbm2ddl.auto=update
cfbamdb.hibernate.show_sql=false
cfbamdb.hibernate.format_sql=false
cfbamdb.hibernate.use_sql_comments=false
cfbamdb.hikari.maximum-pool-size=10
cfbamdb.hikari.minimum-idle=2

# Global defaults
jakarta.persistence.create-database-schemas=true

hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.use_sql_comments=false

hikari.auto-commit=false
hikari.maximum-pool-size=10
hikari.minimum-idle=2

# CFSecDb compiled-in mappings; do not change!
cfsecdb.hibernate.default_schema=cfsecdb
cfsecdb.hikari.pool-name=CFSecDbHikariCP

# CFIntDb compiled-in mappings; do not change!
cfintdb.hibernate.default_schema=cfintdb
cfintdb.hikari.pool-name=CFIntDbHikariCP

# CFBamDb compiled-in mappings; do not change!
cfbamdb.hibernate.default_schema=cfbamdb
cfbamdb.hikari.pool-name=CFBamDbHikariCP

